= Notes
:toc: left
:toclevels: 5

Make is a build system that is used to compile C/C++ programs.
It allows us to have various useful features such as recompiling only what is changed, executing instructions, conditionally compiling something etc.

This tutorial compatible version 3 and 4 of `Make`.

You can get `make` from `apt`.

== Makefile syntax
A `Makefile` has a set of rules which look like:

[source,make]
----
targets: prerequisites
    command
    ...
    command
----

[IMPORTANT]
====
`Makefile` must be tab-indented and not spaces
====

* `targets` are filenames, seperated by spaces.
Normally, there's one per rule.
* `command`(s) are series of steps used to make the targets from the pre-requisites.
They need to be tab-indented(not space).
* `prerequisites` are filenames, seperated by spaces, which need to exist in order for the commands to be run.
They are also called `dependencies`.

A target is run when:

* it has no dependency, and the target file doesn't exist
* it has a dependency, and the dependency file:
** exists
*** but the target file doesn't exist
*** and the dependency file is newer than the target file
** doesn't exist but there is a dependency target in the makefile which doesn't run any commands which fails.
+
[NOTE]
====
Here, the dependency target is run first, and then the actual target is run as long as none of the commands inside the dependency target fail.
====
+
[CAUTION]
====
The only thing that matters here is if the commands under the dependecy's target execute succesfully or not.
It doesn't matter *if they don't create the dependency file*.
Hence, even if the dependency file is not created, as long as there's a dependency target that doesn't run any command that fails, the target will run.
====

A target is not executed when:

* it has no dependency, and the target file exists
* it has a dependency and the dependency file
** exists but is older than the target file
** doesn't exists and
*** there is no target to build it
*** the dependency's target executes a command that fails.

[NOTE]
====
The above rules gives rise to any interesting scenario.
For example, you have compiled you binary, and then you edit the binary.
Still if you run `make` whether the target of the binary will be re-run or not depends on the above rules.
Make doesn't care if you manually edited the binary.
====

[IMPORTANT]
====
Here when we say older/newer we are referring to the last file modfication time which could be the time of file creation or edit whichever happened latest.
====

== Running make file

The first target is the default target, hence if you do:
----
make
----
only that will be executed.

To run a specific target:
----
make <target>
----

=== `clean`
By convention, we write `clean` as a target to remove the output of all the other targets.
Its not a keyword.

[NOTE]
====
`clean` is not written at the top of the make file and it is not a dependency of any other targets.
====
