hello1: # will run as long as "hello1" doesn't exist
	touch hello1

hello2: 
# running "make" will (try to) execute just the target at the top(and its pre-requisites)
# here "hello1" is the target at the top and it has no pre-requisites
# you can independently run any target by "make <target_name>"
	touch hello2

