hello: # "hello" is the target, there are no pre-requisites
	echo "This line will run this time coz there is no file by name 'hello' in this directory"
	touch hello # creating file "hello"
	echo "Now 'hello' is created, and till you delete it, if you run the command again, you'll not see these messages"
